name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Pipeline Template
        uses: tipson007/pipeline-templates/.github/workflows/main.yml@main
